server:
  port: 8085

spring:
  application:
    name: two-pigs-story-backend-service-post
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: aIUKaryCc0520.
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: dev

knife4j:
  enable: true
  setting:
    language: zh-CN