spring:
  application:
    name: two-pigs-story-backend
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: aIUKaryCc0520.
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      name: user
      password: 123456

server:
  port: 8080

mybatis-plus:
  mapper-locations: classpath:mapperXML/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false
    local-cache-scope: statement

# 暴露所有监控信息为HTTP
management:
  endpoints:
    enabled-by-default: true # 默认开启所有监控端点信息
    web:
      exposure:
        include: '*' # 以web方式暴露所有端点

knife4j:
  enable: true
  setting:
    language: zh-CN

jwt:
  secret: 1234567890123456
  expirationTime: 604800
  issuer: springboot3-security
  header: Authorization
  tokenHead: Bearer